name: CI

# Запускаем воркфлоу на каждый пуш в репозиторий
on: push

jobs:
  build:
    # Задаем операционную систему для выполнения (последняя Ubuntu)
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Выполняем нашу команду из Makefile
      - name: Run Make say-hello
        run: make say-hello
